### A Pluto.jl notebook ###
# v0.17.4

using Markdown
using InteractiveUtils

# ╔═╡ d0cfd4d6-fd6e-423c-b6f0-96235cabcf5a
using TikzPictures

# ╔═╡ 3f422fe5-ff3d-4360-9e24-4fe175aae13c
using CapAndHomalg

# ╔═╡ 14e8bfae-b353-4bb1-8a5f-85fc6cdaa86b
md"""
## A mechanical proof of a statement about images of pullbacks in Abelian categories

This notebook demonstrates a completely mechanical proof of a proposition valid in any Abelian category. We rely on the impressive paper:

Sebastian Posur, _On Free Abelian Categories For Theorem Proving_, Journal of Pure and Applied Algebra 226 (2022), no. 7, 106994 ([arXiv:2103.08379](https://sebastianpos.github.io/On-free-abelian-categories-for-theorem-proving/))

We refer to this notebook in

Mohamed Barakat and Lukas Kühne, _Computing the nonfree locus of the moduli space of arrangements and Terao's freeness conjecture_

in order to mechanically prove the following generalization of Proposition 5.4 in loc. cit.:

**Prop.** In any Abelian category the image embedding $\iota$ of the pullback of a morphism $\omega: T \to D$ along a morphism $\jmath: S \to D$ defines the same subobject of $S$ as the kernel $\varkappa$ of the composition of $\jmath$ with the cokernel projection $\varepsilon$ of $\omega$.
"""

# ╔═╡ cba00b54-8569-4ddc-9450-aac42ec7de85
TikzPicture(L"""
    \node(DerA) {$P$};
    \node(SumT) at (4,0) {$T$};
    \node(DerS) at (0,-2) {$S$};
    \node(SumS) at (4,-2) {$D$};
    \node(coker) at (4,-4) {$C = \mathrm{coker} \omega$};
    \node(K) at (-2,0) {$K$};
    \node(K') at (-4,0) {$K'$};
    \draw[->] (SumT) -- node[right]{$\omega$} (SumS);
    \draw[->] (DerS) -- node[above]{$\jmath$} (SumS);
    \draw[->] (DerA) -- node[right]{$\rho$} (DerS);
    \draw[->] (DerA) -- (SumT);
    \draw[->>] (SumS) -- node[right]{$\varepsilon$} (coker);
    \draw[->] (DerS) -- node[below left]{$\varepsilon \circ \jmath$} (coker);
    \draw[->>] (DerA) -- (K);
    \draw[right hook->] (K) -- node[right]{$\iota$} (DerS);
    \draw[right hook->] (K') -- node[below left]{$\varkappa$} (DerS);"""
, options="scale=1.5", preamble="\\usepackage{amssymb}\\usetikzlibrary{arrows}")


# ╔═╡ f3010353-ca1f-4a77-8e59-938f0902639d
md"""
The Julia package [`CapAndHomalg`](https://homalg-project.github.io/pkg/CapAndHomalg.jl/) provides simplified access to the repositories of the `GAP` packages hosted on the [GitHub organization homalg-project](https://homalg-project.github.io/):
"""

# ╔═╡ 5b0c4112-008b-4ef2-a720-e58272a8101b
md"""
We start by loading the package [`Algebroids`](https://homalg-project.github.io/pkg/Algebroids/) which relies on the package [`QPA2`](http://github.com/sunnyquiver/QPA2/) and allows the construction of finitely presented categories and finilely presented linear categories:
"""

# ╔═╡ 9b51d9d4-b297-4eab-b8dc-2eb0bbdfc526
LoadPackage( "Algebroids" )

# ╔═╡ 6b814be9-7430-4983-8330-0e32ab49b95c
md"""
Define the quiver $q$ with three objects $S,D,T$ and two generating morphisms $S \xrightarrow{\jmath} D \xleftarrow{\omega} T$:
"""

# ╔═╡ 5c8cec3c-d4b9-4727-ab91-aef184ca7109
q = RightQuiver( "q(S,D,T)[j:S->D,omega:T->D]" )

# ╔═╡ 2cf4b5ec-65ee-43ce-b3fa-206df0ed394b
md"""
First we use the category constructor `FreeCategory` to construct the _category closure_ of the quiver $q$, i.e., the _free category_ $Fq$ generated by the quiver $q$:
"""

# ╔═╡ 013e3098-ad3b-4bd2-9402-ec98702acd94
Fq = FreeCategory( q )

# ╔═╡ 19432085-ace6-4a3f-98e0-45ffffd000c2
md"""
Then we use the category constructor $\mathbb{Z}[-]$ to construct the _pre-additive closure_ (or _$\mathbb{Z}$-linear closure_) $\mathbb{Z}q$ of $Fq$:
"""

# ╔═╡ 79093f45-f8d2-49be-93ff-409469a1fb51
ℤ = HomalgRingOfIntegers( )

# ╔═╡ 469433a6-6ab4-41d8-beed-e9ac45c6b420
ℤq = ℤ[Fq]

# ╔═╡ df766037-6159-4419-9e2c-d524fce4b6fb
md"""
The package [`FreydCategoriesForCAP`](https://homalg-project.github.io/pkg/FreydCategoriesForCAP/) gives us access to the two further category constructors `AdditiveClosure` and `AdelmanCategory`:
"""

# ╔═╡ 45015bd8-1d79-46e9-9d69-fad69af2a6f4
LoadPackage( "FreydCategoriesForCAP" )

# ╔═╡ c45124b9-2b4b-45b7-b506-9b0f30b1ad50
md"""
The category constructor `AdditiveClosure` returns the _additive closure_ of the given pre-additive category $\mathbb{Z} q$, i.e., closes it under direct sums:
"""

# ╔═╡ b265e4ac-7587-4929-8c7f-da7b9aa283d5
ℤq_add = AdditiveClosure( ℤq )

# ╔═╡ 3709b80b-d137-451e-bd93-01897885bbf5
md"""
Finally, the category constructor `AdelmanCategory` returns the _Abelian closure_ category of the additive category ℤq_add, which is nothing but the _free Abelian category_ generated by the quiver $q$:
"""

# ╔═╡ 3b2a9abc-7461-4af5-809b-a1416aa1e8fe
ℤq_abel = AdelmanCategory( ℤq_add )

# ╔═╡ 3e3c6e26-f6e0-4ed9-a294-6fcf4c69a13c
md"""
Now we view the arrows $\jmath$ and $\mu$ as morphisms in the free Abelian category generated by the quiver $q$:
"""

# ╔═╡ 6d5143a7-eb2b-401c-bcc0-35b15f6947cc
ȷ = ℤq.j / ℤq_add / ℤq_abel

# ╔═╡ fc838213-b7eb-42ca-844f-b607ef2e1aa4
ω = ℤq.omega / ℤq_add / ℤq_abel

# ╔═╡ b244e9ea-8fc5-4950-96a6-d1da2cf53423
md"""
Now we compute the pullback $\rho$ of $\omega$ along $\jmath$:
"""

# ╔═╡ e79fe580-4cd7-4a47-9067-b6c5c2145cde
ρ = ProjectionInFactorOfFiberProduct( GapObj( [ ȷ, ω ] ), 1 )

# ╔═╡ 53b5fe10-0b95-4e72-8272-4b4649de7295
Range( ρ ) == Source( ȷ )

# ╔═╡ 2c5b4b4b-f68c-48f6-86ad-717774b8df37
md"""
The image embedding of $\rho$ is the monic part of epi-mono-factorization of $\rho$:
"""

# ╔═╡ b86d6041-c341-49f3-92d5-172ebea6ffb9
ι = ImageEmbedding( ρ )

# ╔═╡ 623fac00-b736-412d-86c9-d72e1ca77a1f
Range( ι ) == Source( ȷ )

# ╔═╡ 1c795631-0461-4f26-a210-b857a7e0d296
md"""
Now we compute the kernel of a composition of $\jmath$ and the cokernel projection of $\mu$:
"""

# ╔═╡ 68341e1a-2dbb-4d58-a499-ec84b8df06ea
δ = PreCompose( ȷ, CokernelProjection( ω ) )

# ╔═╡ 88ac3c1a-d810-4261-b0d4-95b11898c711
κ = KernelEmbedding( δ )

# ╔═╡ c3fbb794-e3a2-45a1-bb88-b3192cfb11c7
Range( κ ) == Range( ι )

# ╔═╡ 666d0e71-d198-4dba-bd56-4aaaca004dd0
md"""
... and finally verify that the two monos $\iota$ and $\varkappa$ define the same subobject of the source of $\jmath$:
"""

# ╔═╡ 9e4614f7-7f3d-4cb1-a707-15162e67b3c9
IsEqualAsSubobjects( ι, κ )

# ╔═╡ 00000000-0000-0000-0000-000000000001
PLUTO_PROJECT_TOML_CONTENTS = """
[deps]
CapAndHomalg = "c4774649-1891-41ea-a883-87141804c57c"
TikzPictures = "37f6aa50-8035-52d0-81c2-5a1d08754b2d"

[compat]
CapAndHomalg = "~1.3.1"
TikzPictures = "~3.4.1"
"""

# ╔═╡ 00000000-0000-0000-0000-000000000002
PLUTO_MANIFEST_TOML_CONTENTS = """
# This file is machine-generated - editing it directly is not advised

julia_version = "1.7.0"
manifest_format = "2.0"

[[deps.ArgTools]]
uuid = "0dad84c5-d112-42e6-8d28-ef12dabb789f"

[[deps.Artifacts]]
uuid = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[[deps.Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[deps.Bzip2_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "19a35467a82e236ff51bc17a3a44b69ef35185a2"
uuid = "6e34b625-4abd-537c-b88f-471c36dfa7a0"
version = "1.0.8+0"

[[deps.Cairo_jll]]
deps = ["Artifacts", "Bzip2_jll", "Fontconfig_jll", "FreeType2_jll", "Glib_jll", "JLLWrappers", "LZO_jll", "Libdl", "Pixman_jll", "Pkg", "Xorg_libXext_jll", "Xorg_libXrender_jll", "Zlib_jll", "libpng_jll"]
git-tree-sha1 = "4b859a208b2397a7a623a03449e4636bdb17bcf2"
uuid = "83423d85-b0ee-5818-9007-b63ccbeb887a"
version = "1.16.1+1"

[[deps.CapAndHomalg]]
deps = ["GAP", "Graphviz_jll", "Markdown", "Pkg", "Singular_jll", "lib4ti2_jll"]
git-tree-sha1 = "f139b5b73fd667adba766942d0a7d8e8617fdc8a"
uuid = "c4774649-1891-41ea-a883-87141804c57c"
version = "1.3.1"

[[deps.CompilerSupportLibraries_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"

[[deps.Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[deps.Downloads]]
deps = ["ArgTools", "LibCURL", "NetworkOptions"]
uuid = "f43a241f-c20a-4ad4-852c-f6b1247861c6"

[[deps.Expat_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "b3bfd02e98aedfa5cf885665493c5598c350cd2f"
uuid = "2e619515-83b5-522b-bb60-26c02a35a201"
version = "2.2.10+0"

[[deps.FLINT_jll]]
deps = ["Artifacts", "GMP_jll", "JLLWrappers", "Libdl", "MPFR_jll", "Pkg"]
git-tree-sha1 = "3cf4b1d707da7721dea6139f8416edca83a4871c"
uuid = "e134572f-a0d5-539d-bddf-3cad8db41a82"
version = "200.800.401+0"

[[deps.Fontconfig_jll]]
deps = ["Artifacts", "Bzip2_jll", "Expat_jll", "FreeType2_jll", "JLLWrappers", "Libdl", "Libuuid_jll", "Pkg", "Zlib_jll"]
git-tree-sha1 = "21efd19106a55620a188615da6d3d06cd7f6ee03"
uuid = "a3f928ae-7b40-5064-980b-68af3947d34b"
version = "2.13.93+0"

[[deps.FreeType2_jll]]
deps = ["Artifacts", "Bzip2_jll", "JLLWrappers", "Libdl", "Pkg", "Zlib_jll"]
git-tree-sha1 = "87eb71354d8ec1a96d4a7636bd57a7347dde3ef9"
uuid = "d7e528f0-a631-5988-bf34-fe36492bcfd7"
version = "2.10.4+0"

[[deps.FriBidi_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "aa31987c2ba8704e23c6c8ba8a4f769d5d7e4f91"
uuid = "559328eb-81f9-559d-9380-de523a88c83c"
version = "1.0.10+0"

[[deps.GAP]]
deps = ["Downloads", "GAP_jll", "GAP_lib_jll", "GAP_pkg_juliainterface_jll", "GMP_jll", "Libdl", "MacroTools", "Markdown", "Pkg", "REPL", "Random"]
git-tree-sha1 = "efe109fc65b0e98e2c764bd2a33eaf747f892476"
uuid = "c863536a-3901-11e9-33e7-d5cd0df7b904"
version = "0.7.2"

[[deps.GAP_jll]]
deps = ["Artifacts", "GMP_jll", "JLLWrappers", "Libdl", "Pkg", "Readline_jll", "Zlib_jll"]
git-tree-sha1 = "06a4a5cb3e612137b7a026a7c468a73433749e4e"
uuid = "5cd7a574-2c56-5be2-91dc-c8bc375b9ddf"
version = "400.1191.1+0"

[[deps.GAP_lib_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "2c1777e6b4b053b7e1d780cb5f6ce71e6318996e"
uuid = "de1ad85e-c930-5cd4-919d-ccd3fcafd1a3"
version = "400.1191.0+0"

[[deps.GAP_pkg_juliainterface_jll]]
deps = ["Artifacts", "GAP_jll", "GAP_lib_jll", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "9e25b3ad75469a746ce23a8173975e3a9a85c216"
uuid = "ba154793-3a7d-51ee-8800-e295b0cf7374"
version = "0.700.100+0"

[[deps.GLPK_jll]]
deps = ["Artifacts", "GMP_jll", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "fe68622f32828aa92275895fdb324a85894a5b1b"
uuid = "e8aa6df9-e6ca-548a-97ff-1f85fc5b8b98"
version = "5.0.1+0"

[[deps.GMP_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "781609d7-10c4-51f6-84f2-b8444358ff6d"

[[deps.Gettext_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "JLLWrappers", "Libdl", "Libiconv_jll", "Pkg", "XML2_jll"]
git-tree-sha1 = "9b02998aba7bf074d14de89f9d37ca24a1a0b046"
uuid = "78b55507-aeef-58d4-861c-77aaff3498b1"
version = "0.21.0+0"

[[deps.Glib_jll]]
deps = ["Artifacts", "Gettext_jll", "JLLWrappers", "Libdl", "Libffi_jll", "Libiconv_jll", "Libmount_jll", "PCRE_jll", "Pkg", "Zlib_jll"]
git-tree-sha1 = "a32d672ac2c967f3deb8a81d828afc739c838a06"
uuid = "7746bdde-850d-59dc-9ae8-88ece973131d"
version = "2.68.3+2"

[[deps.Graphite2_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "344bf40dcab1073aca04aa0df4fb092f920e4011"
uuid = "3b182d85-2403-5c21-9c21-1e1f0cc25472"
version = "1.3.14+0"

[[deps.Graphviz_jll]]
deps = ["Artifacts", "Cairo_jll", "Expat_jll", "JLLWrappers", "Libdl", "Pango_jll", "Pkg"]
git-tree-sha1 = "cb399bbf057084282d7036312b1dc7a0eb103bf4"
uuid = "3c863552-8265-54e4-a6dc-903eb78fde85"
version = "2.49.3+1"

[[deps.HarfBuzz_jll]]
deps = ["Artifacts", "Cairo_jll", "Fontconfig_jll", "FreeType2_jll", "Glib_jll", "Graphite2_jll", "JLLWrappers", "Libdl", "Libffi_jll", "Pkg"]
git-tree-sha1 = "129acf094d168394e80ee1dc4bc06ec835e510a3"
uuid = "2e76f6c2-a576-52d4-95c1-20adfe4de566"
version = "2.8.1+1"

[[deps.InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[deps.JLLWrappers]]
deps = ["Preferences"]
git-tree-sha1 = "642a199af8b68253517b80bd3bfd17eb4e84df6e"
uuid = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
version = "1.3.0"

[[deps.JpegTurbo_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "d735490ac75c5cb9f1b00d8b5509c11984dc6943"
uuid = "aacddb02-875f-59d6-b918-886e6ef4fbf8"
version = "2.1.0+0"

[[deps.LZO_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "e5b909bcf985c5e2605737d2ce278ed791b89be6"
uuid = "dd4b983a-f0e5-5f8d-a1b7-129d4a5fb1ac"
version = "2.10.1+0"

[[deps.LaTeXStrings]]
git-tree-sha1 = "f2355693d6778a178ade15952b7ac47a4ff97996"
uuid = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
version = "1.3.0"

[[deps.LibCURL]]
deps = ["LibCURL_jll", "MozillaCACerts_jll"]
uuid = "b27032c2-a3e7-50c8-80cd-2d36dbcbfd21"

[[deps.LibCURL_jll]]
deps = ["Artifacts", "LibSSH2_jll", "Libdl", "MbedTLS_jll", "Zlib_jll", "nghttp2_jll"]
uuid = "deac9b47-8bc7-5906-a0fe-35ac56dc84c0"

[[deps.LibGit2]]
deps = ["Base64", "NetworkOptions", "Printf", "SHA"]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[deps.LibSSH2_jll]]
deps = ["Artifacts", "Libdl", "MbedTLS_jll"]
uuid = "29816b5a-b9ab-546f-933c-edad1886dfa8"

[[deps.Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[deps.Libffi_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "0b4a5d71f3e5200a7dff793393e09dfc2d874290"
uuid = "e9f186c6-92d2-5b65-8a66-fee21dc1b490"
version = "3.2.2+1"

[[deps.Libgcrypt_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Libgpg_error_jll", "Pkg"]
git-tree-sha1 = "64613c82a59c120435c067c2b809fc61cf5166ae"
uuid = "d4300ac3-e22c-5743-9152-c294e39db1e4"
version = "1.8.7+0"

[[deps.Libgpg_error_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "c333716e46366857753e273ce6a69ee0945a6db9"
uuid = "7add5ba3-2f88-524e-9cd5-f83b8a55f7b8"
version = "1.42.0+0"

[[deps.Libiconv_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "42b62845d70a619f063a7da093d995ec8e15e778"
uuid = "94ce4f54-9a6c-5748-9c1c-f9c7231a4531"
version = "1.16.1+1"

[[deps.Libmount_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "9c30530bf0effd46e15e0fdcf2b8636e78cbbd73"
uuid = "4b2f31a3-9ecc-558c-b454-b3730dcb73e9"
version = "2.35.0+0"

[[deps.Libtiff_jll]]
deps = ["Artifacts", "JLLWrappers", "JpegTurbo_jll", "Libdl", "Pkg", "Zlib_jll", "Zstd_jll"]
git-tree-sha1 = "340e257aada13f95f98ee352d316c3bed37c8ab9"
uuid = "89763e89-9b03-5906-acba-b20f662cd828"
version = "4.3.0+0"

[[deps.Libuuid_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "7f3efec06033682db852f8b3bc3c1d2b0a0ab066"
uuid = "38a345b3-de98-5d2b-a5d3-14cd9215e700"
version = "2.36.0+0"

[[deps.LittleCMS_jll]]
deps = ["Artifacts", "JLLWrappers", "JpegTurbo_jll", "Libdl", "Libtiff_jll", "Pkg"]
git-tree-sha1 = "110897e7db2d6836be22c18bffd9422218ee6284"
uuid = "d3a379c0-f9a3-5b72-a4c0-6bf4d2e8af0f"
version = "2.12.0+0"

[[deps.Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[deps.MPFR_jll]]
deps = ["Artifacts", "GMP_jll", "Libdl"]
uuid = "3a97d323-0669-5f0c-9066-3539efd106a3"

[[deps.MacroTools]]
deps = ["Markdown", "Random"]
git-tree-sha1 = "3d3e902b31198a27340d0bf00d6ac452866021cf"
uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
version = "0.5.9"

[[deps.Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[deps.MbedTLS_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "c8ffd9c3-330d-5841-b78e-0817d7145fa1"

[[deps.MozillaCACerts_jll]]
uuid = "14a3606d-f60d-562e-9121-12d972cd8159"

[[deps.Ncurses_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "e3fb71f3c971fdc8523f9ef3906691124f3048a2"
uuid = "68e3532b-a499-55ff-9963-d1c0c0748b3a"
version = "6.2.0+0"

[[deps.NetworkOptions]]
uuid = "ca575930-c2e3-43a9-ace4-1e988b2c1908"

[[deps.OpenJpeg_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Libtiff_jll", "LittleCMS_jll", "Pkg", "libpng_jll"]
git-tree-sha1 = "76374b6e7f632c130e78100b166e5a48464256f8"
uuid = "643b3616-a352-519d-856d-80112ee9badc"
version = "2.4.0+0"

[[deps.PCRE_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "b2a7af664e098055a7529ad1a900ded962bca488"
uuid = "2f80f16e-611a-54ab-bc61-aa92de5b98fc"
version = "8.44.0+0"

[[deps.Pango_jll]]
deps = ["Artifacts", "Cairo_jll", "Fontconfig_jll", "FreeType2_jll", "FriBidi_jll", "Glib_jll", "HarfBuzz_jll", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "9bc1871464b12ed19297fbc56c4fb4ba84988b0d"
uuid = "36c8627f-9965-5494-a995-c6b170f724f3"
version = "1.47.0+0"

[[deps.Pixman_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "b4f5d02549a10e20780a24fce72bea96b6329e29"
uuid = "30392449-352a-5448-841d-b1acce4e97dc"
version = "0.40.1+0"

[[deps.Pkg]]
deps = ["Artifacts", "Dates", "Downloads", "LibGit2", "Libdl", "Logging", "Markdown", "Printf", "REPL", "Random", "SHA", "Serialization", "TOML", "Tar", "UUIDs", "p7zip_jll"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[deps.Poppler_jll]]
deps = ["Artifacts", "Cairo_jll", "Fontconfig_jll", "Glib_jll", "JLLWrappers", "JpegTurbo_jll", "Libdl", "Libtiff_jll", "OpenJpeg_jll", "Pkg", "libpng_jll"]
git-tree-sha1 = "e11443687ac151ac6ef6699eb75f964bed8e1faa"
uuid = "9c32591e-4766-534b-9725-b71a8799265b"
version = "0.87.0+2"

[[deps.Preferences]]
deps = ["TOML"]
git-tree-sha1 = "2cf929d64681236a2e074ffafb8d568733d2e6af"
uuid = "21216c6a-2e73-6563-6e65-726566657250"
version = "1.2.3"

[[deps.Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[deps.REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets", "Unicode"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[deps.Random]]
deps = ["SHA", "Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[deps.Readline_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Ncurses_jll", "Pkg"]
git-tree-sha1 = "7cfd44e2889fcabf8ee80dad89bccb3756d4e778"
uuid = "05236dd9-4125-5232-aa7c-9ec0c9b2c25a"
version = "8.1.1+1"

[[deps.Requires]]
deps = ["UUIDs"]
git-tree-sha1 = "8f82019e525f4d5c669692772a6f4b0a58b06a6a"
uuid = "ae029012-a4dd-5104-9daa-d747884805df"
version = "1.2.0"

[[deps.SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[deps.Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[deps.Singular_jll]]
deps = ["Artifacts", "FLINT_jll", "GMP_jll", "JLLWrappers", "Libdl", "MPFR_jll", "Pkg", "cddlib_jll"]
git-tree-sha1 = "5d3fd3ffb962a36a6ed60274eb8610fad4438870"
uuid = "43d676ae-4934-50ba-8046-7a96366d613b"
version = "402.101.201+0"

[[deps.Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[deps.TOML]]
deps = ["Dates"]
uuid = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[[deps.Tar]]
deps = ["ArgTools", "SHA"]
uuid = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"

[[deps.Tectonic]]
deps = ["Pkg"]
git-tree-sha1 = "acf12eccb390a78653ee805cd527898f01f78a85"
uuid = "9ac5f52a-99c6-489f-af81-462ef484790f"
version = "0.6.1"

[[deps.TikzPictures]]
deps = ["LaTeXStrings", "Poppler_jll", "Requires", "Tectonic"]
git-tree-sha1 = "a08671c0979063a437378f6410bb75a465f3cd1c"
uuid = "37f6aa50-8035-52d0-81c2-5a1d08754b2d"
version = "3.4.1"

[[deps.UUIDs]]
deps = ["Random", "SHA"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[deps.Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[deps.XML2_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Libiconv_jll", "Pkg", "Zlib_jll"]
git-tree-sha1 = "1acf5bdf07aa0907e0a37d3718bb88d4b687b74a"
uuid = "02c8fc9c-b97f-50b9-bbe4-9be30ff0a78a"
version = "2.9.12+0"

[[deps.XSLT_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Libgcrypt_jll", "Libgpg_error_jll", "Libiconv_jll", "Pkg", "XML2_jll", "Zlib_jll"]
git-tree-sha1 = "91844873c4085240b95e795f692c4cec4d805f8a"
uuid = "aed1982a-8fda-507f-9586-7b0439959a61"
version = "1.1.34+0"

[[deps.Xorg_libX11_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libxcb_jll", "Xorg_xtrans_jll"]
git-tree-sha1 = "5be649d550f3f4b95308bf0183b82e2582876527"
uuid = "4f6342f7-b3d2-589e-9d20-edeb45f2b2bc"
version = "1.6.9+4"

[[deps.Xorg_libXau_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "4e490d5c960c314f33885790ed410ff3a94ce67e"
uuid = "0c0b7dd1-d40b-584c-a123-a41640f87eec"
version = "1.0.9+4"

[[deps.Xorg_libXdmcp_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "4fe47bd2247248125c428978740e18a681372dd4"
uuid = "a3789734-cfe1-5b06-b2d0-1dd0d9d62d05"
version = "1.1.3+4"

[[deps.Xorg_libXext_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libX11_jll"]
git-tree-sha1 = "b7c0aa8c376b31e4852b360222848637f481f8c3"
uuid = "1082639a-0dae-5f34-9b06-72781eeb8cb3"
version = "1.3.4+4"

[[deps.Xorg_libXrender_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Xorg_libX11_jll"]
git-tree-sha1 = "19560f30fd49f4d4efbe7002a1037f8c43d43b96"
uuid = "ea2f1a96-1ddc-540d-b46f-429655e07cfa"
version = "0.9.10+4"

[[deps.Xorg_libpthread_stubs_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "6783737e45d3c59a4a4c4091f5f88cdcf0908cbb"
uuid = "14d82f49-176c-5ed1-bb49-ad3f5cbd8c74"
version = "0.1.0+3"

[[deps.Xorg_libxcb_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "XSLT_jll", "Xorg_libXau_jll", "Xorg_libXdmcp_jll", "Xorg_libpthread_stubs_jll"]
git-tree-sha1 = "daf17f441228e7a3833846cd048892861cff16d6"
uuid = "c7cfdc94-dc32-55de-ac96-5a1b8d977c5b"
version = "1.13.0+3"

[[deps.Xorg_xtrans_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "79c31e7844f6ecf779705fbc12146eb190b7d845"
uuid = "c5fb5394-a638-5e4d-96e5-b29de1b5cf10"
version = "1.4.0+3"

[[deps.Zlib_jll]]
deps = ["Libdl"]
uuid = "83775a58-1f1d-513f-b197-d71354ab007a"

[[deps.Zstd_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "cc4bf3fdde8b7e3e9fa0351bdeedba1cf3b7f6e6"
uuid = "3161d3a3-bdf6-5164-811a-617609db77b4"
version = "1.5.0+0"

[[deps.cddlib_jll]]
deps = ["Artifacts", "GMP_jll", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "c25e5fe14395ea7b1d702f4eb90c52bdf50e3450"
uuid = "f07e07eb-5685-515a-97c8-3014f6152feb"
version = "0.94.13+0"

[[deps.lib4ti2_jll]]
deps = ["Artifacts", "GLPK_jll", "GMP_jll", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "79116185def638e73ea3d88ca6c10e210a1dc183"
uuid = "1493ae25-0f90-5c0e-a06c-8c5077d6d66f"
version = "1.6.10+0"

[[deps.libpng_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg", "Zlib_jll"]
git-tree-sha1 = "94d180a6d2b5e55e447e2d27a29ed04fe79eb30c"
uuid = "b53b4c65-9356-5827-b1ea-8c7a1a84506f"
version = "1.6.38+0"

[[deps.nghttp2_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "8e850ede-7688-5339-a07c-302acd2aaf8d"

[[deps.p7zip_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "3f19e933-33d8-53b3-aaab-bd5110c3b7a0"
"""

# ╔═╡ Cell order:
# ╟─14e8bfae-b353-4bb1-8a5f-85fc6cdaa86b
# ╟─d0cfd4d6-fd6e-423c-b6f0-96235cabcf5a
# ╟─cba00b54-8569-4ddc-9450-aac42ec7de85
# ╟─f3010353-ca1f-4a77-8e59-938f0902639d
# ╠═3f422fe5-ff3d-4360-9e24-4fe175aae13c
# ╟─5b0c4112-008b-4ef2-a720-e58272a8101b
# ╠═9b51d9d4-b297-4eab-b8dc-2eb0bbdfc526
# ╟─6b814be9-7430-4983-8330-0e32ab49b95c
# ╠═5c8cec3c-d4b9-4727-ab91-aef184ca7109
# ╟─2cf4b5ec-65ee-43ce-b3fa-206df0ed394b
# ╠═013e3098-ad3b-4bd2-9402-ec98702acd94
# ╟─19432085-ace6-4a3f-98e0-45ffffd000c2
# ╠═79093f45-f8d2-49be-93ff-409469a1fb51
# ╠═469433a6-6ab4-41d8-beed-e9ac45c6b420
# ╟─df766037-6159-4419-9e2c-d524fce4b6fb
# ╠═45015bd8-1d79-46e9-9d69-fad69af2a6f4
# ╟─c45124b9-2b4b-45b7-b506-9b0f30b1ad50
# ╠═b265e4ac-7587-4929-8c7f-da7b9aa283d5
# ╟─3709b80b-d137-451e-bd93-01897885bbf5
# ╠═3b2a9abc-7461-4af5-809b-a1416aa1e8fe
# ╟─3e3c6e26-f6e0-4ed9-a294-6fcf4c69a13c
# ╠═6d5143a7-eb2b-401c-bcc0-35b15f6947cc
# ╠═fc838213-b7eb-42ca-844f-b607ef2e1aa4
# ╟─b244e9ea-8fc5-4950-96a6-d1da2cf53423
# ╠═e79fe580-4cd7-4a47-9067-b6c5c2145cde
# ╠═53b5fe10-0b95-4e72-8272-4b4649de7295
# ╟─2c5b4b4b-f68c-48f6-86ad-717774b8df37
# ╠═b86d6041-c341-49f3-92d5-172ebea6ffb9
# ╠═623fac00-b736-412d-86c9-d72e1ca77a1f
# ╟─1c795631-0461-4f26-a210-b857a7e0d296
# ╠═68341e1a-2dbb-4d58-a499-ec84b8df06ea
# ╠═88ac3c1a-d810-4261-b0d4-95b11898c711
# ╠═c3fbb794-e3a2-45a1-bb88-b3192cfb11c7
# ╟─666d0e71-d198-4dba-bd56-4aaaca004dd0
# ╠═9e4614f7-7f3d-4cb1-a707-15162e67b3c9
# ╟─00000000-0000-0000-0000-000000000001
# ╟─00000000-0000-0000-0000-000000000002
