name: Trigger builds on mybinder

on:
  push:
    branches:
      - "master"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # keep workflow active even if repository has no activity for 60 days (do not execute for pull requests)
      - run: '[ "$GITHUB_EVENT_NAME" = "pull_request" ] || curl --fail -X PUT -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/$GITHUB_REPOSITORY/actions/workflows/trigger-mybinder-build.yml/enable'
      - run: |
          [ $GITHUB_REPOSITORY = "homalg-project/CapAndHomalgNotebooks" ] || exit 1
          #curl -L https://mybinder.org/build/gh/homalg-project/CapAndHomalgNotebooks/master
          #curl -L https://gke.mybinder.org/build/gh/homalg-project/CapAndHomalgNotebooks/master
          #curl -L https://ovh.mybinder.org/build/gh/homalg-project/CapAndHomalgNotebooks/master
          # we currently link directly to gesis
          curl -L https://gesis.mybinder.org/build/gh/homalg-project/CapAndHomalgNotebooks/master
          #curl -L https://turing.mybinder.org/build/gh/homalg-project/CapAndHomalgNotebooks/master
